Update Klipper v0.13.0
* stm32: Add support for USART6 on STM32F401

STM32F401 has USART6 on PA12/PA11 and PC7/PC6 with alternate
function mapping AF08. This can be used, for example, to connect
to the Elegoo Neptune 3, where PA12/PA11 are wired to an RJ10 plug
going to the stock screen.

Signed-off-by: Marius Petcu <marius@petcu.me>

* gcode_macro: Expand template syntax errors (#6839)

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* axis_twist_compensation: Remove the auto parameter
from axis_twist_compensation

Signed-off-by: Jorge Apaza Merma <yochiwarez@gmail.com>

* docs: Note AXIS_TWIST_COMPENSATION_CALIBRATE AUTO removal in Config_Changes.md

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* input_shaper: Fix for polar kinematics

Forward post_cb calls from itersolve to the original kinematics.

Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

* axis_twist_compensation: allow compensating both axis at once

Restores the behavior before #6739 since people seemed to rely on it,
even if the math is not exact.

Signed-off-by: Philippe Daouadi <philippe@ud2.org>

* load_cell: Load cell gram scale (#6729)

* Add gram scale features to load_cell
* Convert sensor counts to grams and make this available via unix socket and object status
* Basic GCodes for tearing and reading the load cell
* Guided Calibration
* Diagnostic gcode to check the health of the load cell
* Update load_cell Documentation
* Add API server load_cell/dump_force endpoint
* Update [load_cell] config with calibration fields
* Add G-Code commands for working with load cells
* Add status reference for load_cell objects

Signed-off-by: Gareth Farrington <gareth@waves.ky>

* buttons: Debounce gcode_button and filament_switch_sensor (#6848)

Add `debounce_delay` config option which sets the debounce time, defaults to 0

Signed-off-by: Gareth Farrington <gareth@waves.ky>

* stepper: Support step on both edges with custom minimum pulse duration

Add support for "step on both edges" to the main stepper_event_full()
code.  This makes that mode of operation available even when the
micro-controller is not compiled for "optimized step on both edges".
It also enables the custom pulse duration support (step_pulse_ticks)
when in "step on both edges" mode.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* stepper: Support disabling optimized "step on both edges" in "make menuconfig"

Add a new "low level option" to allow users to configure if they want
to optimize for Trinamic drivers or traditional stepper motor drivers.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* buttons: fixes incorrect parameters

Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>

* config: Add LED definitions to generic-bigtreetech-skr-mini-mz.cfg

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* fan_generic: Fix handling of template rendering errors

Make sure to assign 'value' on a rendering error to avoid an internal
error.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* output_pin: Fix handling of template rendering errors

Make sure to assign 'value' on a rendering error to avoid an internal
error.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* rp2040: define spi bus on pins 12,11,10

Mellow FLY SHT36 Pro toolboard uses those pins

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* stm32: Added PH13/14 CAN pin option for stm32h743 (#6857)

Added the option to select PH13/PH14 as CAN pins.

Signed-off-by:  Christoph Frei <fryakatkop@gmail.com>

* ldc_1612: Supports configurable external crystal frequency (#6734)

You can use the 40Mhz crystal oscillator recommended by TI official manual to get the best performance.
refer to: [ldc1612.pdf](https://www.ti.com/cn/lit/ds/symlink/ldc1612.pdf) 7.3.4

Signed-off-by: Xiaokui Zhao <xiaok@zxkxzk.cn>

* docs: Fix typos in installation.md

Fixed typos, hyphenation, and minor phrasing for better readability.

Signed-off-by: Tobias Rumiz <TobiasRumiz@gmail.com>

* docs: Fix typo in docs generation documentation

Signed-off-by: Russell Cloran <rcloran@gmail.com>

* docs: Fix link syntax typo for bed_screws

Signed-off-by: Russell Cloran <rcloran@gmail.com>

* stm32: Fix RESERVE_PINS_CAN pin ordering in fdcan.c

Always report the reserved pins in the same order (rx,tx).

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* stm32: Add support for additional i2c bus

Signed-off-by: Russell Cloran <rcloran@gmail.com>

* stm32: Turn on can.c error interrupts

It seems both ERRIE and LECIE must be enabled to get hardware error
interrupts.  Without this, the rx_error and tx_error reports are
likely to always be zero.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* output_pin: Make it possible to assign dicts/lists as template parameters

The output_pin template code has a cache to speed up duplicate
rendering of templates.  However, this cache doesn't work if one of
the parameters is a Python list or dictionary.  Just disable the cache
in this case.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* mkdocs-requirements: Update to Jinja 3.1.6

A security vulnerability was found in Jinja 3.1.5 .  The software is
not impacted by this vulnerability, but there is no harm in updating
to the fixed version.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* icm20948: Fix sample rate and accels scale selection

To set a value in the SET_ACCEL_CONFIG register, you must first go to BANK_2.

Signed-off-by: Maksim Bolgov maksim8024@gmail.com

* icm20948: Transition from 8g to 16g accels scale

During standard resonance measurements, the icm20948 in 8g mode may reach the accels max threshold.

Signed-off-by: Maksim Bolgov maksim8024@gmail.com

* icm20948: Formatting refactor

Signed-off-by: Maksim Bolgov maksim8024@gmail.com

* adxl345: Allow read and write 127 register address

icm20948 accelerometer has an ACCEL_CONFIG register at address 127

Signed-off-by: Maksim Bolgov maksim8024@gmail.com

* docs: Add icm20948 description

Signed-off-by: Maksim Bolgov maksim8024@gmail.com

* temperature_combined: delay initialization

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* temperature_combined: avoid crash with temperature monitors

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* axis_twist_compensation: Fix AttributeError on klippy connect state (#6881)

Object 'configfile' has no attribute 'error'

Signed-off-by: Maksim Bolgov <maksim8024@gmail.com>

* docs: Fixup G-Codes.md so that sections are sorted alphabetically

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* i2c_software: Fix i2c_delay()

The i2c_delay() function did not properly handle counter rollovers.
It also performed an expensive run-time divide.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* force_move: Support a SET_HOMED parameter to SET_KINEMATIC_POSITION

Commit 70838797 added support for clearing the homing state in
SET_KINEMATIC_POSITION commands.  However, it can be difficult to use
that support as the default for SET_KINEMATIC_POSITION is to set all
axes as homed.

Add a new SET_HOMED parameter to allow one to explicitly request which
axes to consider in a homed state.

Also introduce a CLEAR_HOMED parameter and prefer that to the existing
CLEAR parameter.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* force_move: Make sure to use lower() on SET_KINEMATIC_POSITION CLEAR_HOMED

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* ci-install: Use prebuilt pru gcc binaries

Don't build the pru binaries directly in the build test cases, instead
use the upstream binaries provided.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* led: Fix off-by-one bug in SET_LED_TEMPLATE INDEX parameter

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* docs: Update Features.md to reflect recent work

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* docs: Note the release of v0.13.0

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Makefile: Don't disable gcc's use-linker-plugin option

This option seems to be confusing ld's region usage checks (builds
that could fit in small chips are being reported as not fitting).  The
option was disabled back in commit 4e8674d5 because it showed worse
results.  However, recent versions of gcc seem to produce the same
results even if this option is enabled, so change the build to avoid
disabling that option on newer versions of gcc (those that have the
-ffat-lto-objects option - which is needed to ensure
compile_time_requests sections can be extracted with objcopy).

The PRU build is dependent on -fuse-linker-plugin, so enable that
option explicitly in its build.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* test: Disable optional features in atmega328 build

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* workflows: Update github build-test.yaml to ubuntu-22.04

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Kconfig: Replace WANT_GPIO_BITBANGING with individual options

Support setting individual options instead of one global option (
WANT_BUTTONS, WANT_TMCUART, WANT_NEOPIXEL, WANT_PULSE_COUNTER,
WANT_HX71X).

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Kconfig: Replace WANT_DISPLAYS with individual options

Support setting WANT_ST7920 and WANT_HD44780 individually.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* avr: Enable gcc -Os option on CONFIG_HAVE_LIMITED_CODE_SIZE

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* stm32: Enable gcc -Os option on CONFIG_HAVE_LIMITED_CODE_SIZE

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Kconfig: Add new WANT_HARD_PWM option to reduce code size

Make it possible to not compile in support for hardware pwm on chips
with small flash sizes.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Kconfig: Add new WANT_SPI option to reduce code size

Make it possible to not compile in support for SPI on chips with small
flash sizes.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Kconfig: Add new WANT_I2C option to reduce code size

Make it possible to not compile in support for I2C on chips with small
flash sizes.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Kconfig: Add new WANT_ADC option to reduce code size

Make it possible to not compile in support for ADC on chips with small
flash sizes.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* stm32: Simplify Makefile

Breakout selection of timer and gpioperiph objects.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Kconfig: Add some user visible comments to the optional features menu

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* atsamd: Enable HAVE_LIMITED_CODE_SIZE on small atsamd chips

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* config: Update generic-bigtreetech-skr-2.cfg - SPI Drivers (#6895)

Added SPI tmc2130 driver config

Signed-off-by: James Hartley <james@hartleyns.com>

* test: Disable all additional features in atmega328 build

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Revert "Makefile: Don't disable gcc's use-linker-plugin option"

This reverts commit 8087200ffe2fbbe62265dd480ce8be67db8349eb.

The change can break the build on some versions of gcc.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* spi_software: respect expected rate

On fast MCU software spi may violate maximally supported by TMC driver rate.

Add dynamic limits to overcome that.

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* software_spi: set rate limiting ticks from the host

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* i2c_software: allow freq adjust

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* i2c_software: reduce gpio calls count

gpio reset calls are heavy.
gpio state are persistent between calls.
Drop useless calls.
Avoid calls if SDA does not changed.

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* i2c_software: pass pulse ticks from host

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* tmc: add missing freewheel config options

Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>

* hall_filament_width_sensor: Add filament switch values to status

`hall_filament_width_sensor` contains a runout sensor object internally.
This exposes those values in the API status result.

```
SEND: {"id":123,"method":"objects/query","params":{"objects":{"hall_filament_width_sensor":["enabled","filament_detected","is_active","Diameter","Raw"]}}}
GOT: b'{"id":123,"result":{"eventtime":199567.823596603,"status":{"hall_filament_width_sensor":{"enabled":true,"filament_detected":true,"is_active":true,"Diameter":1.9499999999999986,"Raw":6113}}}}'
```

The duplication of `is_active` and `enabled` seems confusing, but both
of these can be independently manipulated by GCode:

```
SEND: {"id":123,"method":"gcode/script","params":{"script":"DISABLE_FILAMENT_WIDTH_SENSOR"}}
GOT: b'{"id":123,"result":{}}'
SEND: {"id":123,"method":"objects/query","params":{"objects":{"hall_filament_width_sensor":["enabled","is_active"]}}}
GOT: b'{"id":123,"result":{"eventtime":199770.446013297,"status":{"hall_filament_width_sensor":{"enabled":true,"is_active":false}}}}'

SEND: {"id":123,"method":"gcode/script","params":{"script":"SET_FILAMENT_SENSOR SENSOR=hall_filament_width_sensor ENABLE=0"}}
GOT: b'{"id":123,"result":{}}'
SEND: {"id":123,"method":"objects/query","params":{"objects":{"hall_filament_width_sensor":["enabled","is_active"]}}}
GOT: b'{"id":123,"result":{"eventtime":199847.927726196,"status":{"hall_filament_width_sensor":{"enabled":false,"is_active":false}}}}'
```

Signed-off-by: Russell Cloran <rcloran@gmail.com>

* docs: Update Config_Changes.md to note software spi is now rate limited

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* stm32: Fix prescaler overflow check in hard_pwm.c

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* stm32: Change hard_pwm.c MAX_PWM to 257

Choose a value for MAX_PWM that avoids an expensive run-time division.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* lcd_hd44780: Make sure nsecs_to_ticks() is always inlined

It is a compile-time calculation that needs to be inlined to work.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* lcd_st7920: Make sure nsecs_to_ticks() is always inlined

It is a compile-time calculation that needs to be inlined to work.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* neopixel: Make sure nsecs_to_ticks() is always inlined

It is a compile-time calculation that needs to be inlined to work.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* Kconfig: Note which chips require software divide operations

Add a new HAVE_SOFTWARE_DIVIDE_REQUIRED that indicates which chips
require software divide.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* check-software-div: Add a new build check for software divide

Update the build checks to include a check for unexpected software
divide operations.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* neopixel: Add comments on timing

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* toolhead: Avoid LookAheadQueue calling back into toolhead class

Avoid lookahead.flush() calling back into toolhead._process_moves().
Instead, rename toolhead._process_moves() to
toolhead._process_lookahead(), have it call lookahead.flush(), and
consistently use it when flushing the lookahead queue.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* toolhead: Avoid toolhead.move() and toolhead._process_moves() in drip_move()

Implement move checking and trapq loading directly from drip_move().
This simplifies the interactions between these components.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* manual_stepper: Implement "drip moves" for manual stepper STOP_ON_ENDSTOP

Currently, `MANUAL_STEPPER STOP_ON_ENDSTOP=1` type commands will move
until hitting the endstop, but it will still always consume the total
amount of move time.  That is, following moves can't be started until
the total possible time of the homing move is completed.

Implement "drip moves" so that the code only schedules the movement in
small segments.  This allows following movements to be scheduled
without a significant delay.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe: Add a default probing_move() function to HomingViaProbeHelper

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe: Add a new ProbeEndstopSessionHelper class

Move the HomingViaProbeHelper() instance from ProbeSessionHelper to a
new ProbeEndstopSessionHelper class.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe: Add a new lookup_minimum_z() helper function

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe: Add a new ProbeParameterHelper class

Split multi-sample config reading from ProbeSessionHelper to a new
ProbeParameterHelper class.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe: Change probing_move() to pass a gcmd instead of (pos, speed)

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe: Convert probing_move() callback to use regular probe sessions system

Use the normal probe_session_start(), run_probe(),
pull_probed_results(), and end_probe_session() API from
ProbeSessionHelper.  This removes the custom probing_move() callback.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe: Add a new LookupZSteppers helper class

Split code to lookup the Z stepper from HomingViaProbeHelper to new
LookupZSteppers class.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe_eddy_current: Do not support QUERY_PROBE command

Report an error if a user issues a QUERY_PROBE command (instead of
always returning not-triggered).

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe_eddy_current: Separate probe style commands from homing operations

Separate homing operations (as called from probe:z_virtual_endstop)
from the normal probe command handling.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

* probe: Remove ProbeEndstopSessionHelper

Have all callers instantiate the individual helper classes directly.

Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

---------

Signed-off-by: Marius Petcu <marius@petcu.me>
Signed-off-by: Timofey Titovets <nefelim4ag@gmail.com>
Signed-off-by: Jorge Apaza Merma <yochiwarez@gmail.com>
Signed-off-by: Kevin O'Connor <kevin@koconnor.net>
Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>
Signed-off-by: Philippe Daouadi <philippe@ud2.org>
Signed-off-by: Gareth Farrington <gareth@waves.ky>
Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>
Signed-off-by: Christoph Frei <fryakatkop@gmail.com>
Signed-off-by: Xiaokui Zhao <xiaok@zxkxzk.cn>
Signed-off-by: Tobias Rumiz <TobiasRumiz@gmail.com>
Signed-off-by: Russell Cloran <rcloran@gmail.com>
Signed-off-by: Maksim Bolgov maksim8024@gmail.com
Signed-off-by: Maksim Bolgov <maksim8024@gmail.com>
Signed-off-by: James Hartley <james@hartleyns.com>
Co-authored-by: Marius Petcu <marius@petcu.me>
Co-authored-by: Timofey Titovets <nefelim4ag@gmail.com>
Co-authored-by: yochiwarez <yochiwarez@gmail.com>
Co-authored-by: Kevin O'Connor <kevin@koconnor.net>
Co-authored-by: Dmitry Butyugin <dmbutyugin@google.com>
Co-authored-by: Philippe Daouadi <philippe@ud2.org>
Co-authored-by: Gareth Farrington <gareth@waves.ky>
Co-authored-by: Pedro Lamas <pedrolamas@gmail.com>
Co-authored-by: FrY Sennberg <fryakatkop@gmail.com>
Co-authored-by: XiaoK <xiaok@zxkxz.cn>
Co-authored-by: Tobias Rumiz <63514002+Ruminini@users.noreply.github.com>
Co-authored-by: Russell Cloran <rcloran@gmail.com>
Co-authored-by: MRX8024 <57844100+MRX8024@users.noreply.github.com>
Co-authored-by: JamesH1978 <87171443+JamesH1978@users.noreply.github.com>